In [2]:
import numpy as np
#1
Avect=np.zeros(10)
print('Vector=\n',Avect)
Avect[5]=1
print('new Vector with 1=\n', Avect)

Vector=
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
new Vector with 1=
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [6]:
#2
Dvect=np.arange(10,50)
print(Dvect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
#3
Vect=np.arange(10)
print('Vector',Vect)
Vect=Vect[::-1]
print('Reverse vector', Vect)

Vector [0 1 2 3 4 5 6 7 8 9]
Reverse vector [9 8 7 6 5 4 3 2 1 0]


In [5]:
#4
mtrx=np.arange(9).reshape(3,3)
print(mtrx)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#5
d=np.nonzero([1,2,0,0,4,0])
print(d)

(array([0, 1, 4], dtype=int64),)


In [8]:
#6
arr=np.random.random((3,3,3,))
print(arr)

[[[0.64237731 0.91946907 0.72933587]
  [0.82833924 0.5305712  0.84819186]
  [0.69464149 0.78180781 0.76374583]]

 [[0.2222123  0.65642424 0.34128514]
  [0.38490958 0.71463811 0.99492724]
  [0.46383291 0.00943899 0.6966343 ]]

 [[0.502376   0.2639376  0.23063532]
  [0.68348805 0.93895057 0.14868436]
  [0.45737759 0.58381448 0.61326506]]]


In [10]:
#7
darray=np.random.random((10,10))
print('10x10\n',darray)
darrayMin=darray.min()
print('min\n',darrayMin)
darrayMax=darray.max()
print('max\n',darrayMax)

10x10
 [[0.52728688 0.50823565 0.39351387 0.15119785 0.86702439 0.19097559
  0.19216846 0.62503896 0.94701808 0.06863289]
 [0.01245326 0.47499792 0.87430887 0.83400681 0.6919444  0.27315585
  0.88327168 0.47961158 0.42631291 0.49819628]
 [0.20179409 0.61459618 0.62345037 0.72622286 0.78975759 0.03603488
  0.10561807 0.66802219 0.74711435 0.22048162]
 [0.68884947 0.84014068 0.64069946 0.40144618 0.2957291  0.68374938
  0.2892395  0.86923178 0.7916267  0.24823489]
 [0.01268474 0.2209452  0.7897663  0.88256986 0.04052187 0.35253016
  0.45520532 0.92867767 0.54372376 0.09071061]
 [0.17001833 0.95799206 0.54512399 0.26700336 0.77751867 0.08676503
  0.43825352 0.51110956 0.76415044 0.28203308]
 [0.0031385  0.42758512 0.36255473 0.51988184 0.2384211  0.26242628
  0.09797754 0.36368943 0.92051597 0.05713082]
 [0.61994934 0.00173065 0.94252375 0.16582344 0.64982088 0.86825009
  0.96893894 0.46426435 0.89792331 0.15193166]
 [0.1799957  0.88977683 0.56559731 0.42883887 0.21993379 0.49781519
  0.2

In [11]:
#8
dv=np.random.random(30)
print(dv)
mv=dv.mean()
print('mean\n',mv)

[0.73011582 0.36552436 0.17965132 0.54732693 0.65986572 0.49452945
 0.77195506 0.56170748 0.04167173 0.13951501 0.98440486 0.78187021
 0.21246722 0.78721495 0.71504125 0.03221508 0.29824935 0.3123867
 0.84711076 0.57990792 0.81004865 0.08086269 0.63165151 0.08603779
 0.59850307 0.25555008 0.27008611 0.397917   0.23366821 0.2477053 ]
mean
 0.455158718528095


In [12]:
#9
N=np.arange(9).reshape(3,3)
N=np.pad(N,pad_width=1, mode='constant', constant_values=0)
print(N)

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


In [13]:
#10
d = np.zeros((8,8),dtype=int)
d[1::2,::2] = 2
d[::2,1::2] = 3
print(d)

[[0 3 0 3 0 3 0 3]
 [2 0 2 0 2 0 2 0]
 [0 3 0 3 0 3 0 3]
 [2 0 2 0 2 0 2 0]
 [0 3 0 3 0 3 0 3]
 [2 0 2 0 2 0 2 0]
 [0 3 0 3 0 3 0 3]
 [2 0 2 0 2 0 2 0]]


In [14]:
#11
N = np.random.random((5,5))
print('matrix\n',N)
N = (N - np.mean (N)) / (np.std (N))
print('normal matrix\n',N)

matrix
 [[0.53281609 0.75229904 0.63547884 0.88535812 0.81458779]
 [0.16234325 0.75881683 0.87732197 0.96157184 0.49734963]
 [0.95329825 0.41828994 0.56484391 0.11056148 0.77733639]
 [0.09841639 0.17376522 0.13894212 0.49034469 0.00498612]
 [0.00205586 0.10278181 0.11735946 0.36639494 0.09865372]]
normal matrix
 [[ 0.24974888  0.92667594  0.56638029  1.33705541  1.11878629]
 [-0.89285968  0.94677806  1.3122704   1.57211301  0.14036357]
 [ 1.54659567 -0.10347152  0.34852875 -1.05256449  1.00389591]
 [-1.09002225 -0.85763215 -0.96503321  0.11875902 -1.37817895]
 [-1.38721642 -1.07655847 -1.03159823 -0.26352553 -1.08929029]]


In [15]:
#12
N = np.arange(11)
print(N)
N[(3 < N) & (N <= 8)] *= -1
print(N)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [16]:
#13
N1 = np.random.randint(0,10,10)
print(N1)
N2 = np.random.randint(0,10,10)
print(N2)
print(np.intersect1d(N1,N2))

[3 1 3 8 5 0 3 3 2 8]
[3 3 4 3 1 3 4 9 9 0]
[0 1 3]


In [17]:
#14
d = np.zeros((5,5))
print(d)
d += np.arange(5)
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [18]:
#15
d = np.linspace(0,1,12,endpoint=True)[1:-1]
print(d)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
