In [1]:
from random import seed
from random import randint
import numpy as np
#1task

print("task 1")

A = np.zeros(10)
A[4] = 1
print (A)

#2-3task

print("task 2-3")

B = np.arange(10,50)
print (B)
B[0] = B[-1] + B[0]
B[-1] = B[0] - B[-1]
B[0] = B[0] - B[-1]
print(B)

#4task

print("task 4")

C = np.arange(0,9)
C = C.reshape(3,3)
print (C)

#5task

print("task 5")

d = [1,2,0,0,4,0]
for i in d:
	if (i != 0):
		print (i)

#6task
print("task 6")

F = np.random.random((3,3,3))
print(F)


#7task
print("task 7")
V = np.random.random((10,10))
a, b = V.min(), V.max()
print("min is:",a, "max is:",b)

#8task

print("task 8")

A = np.random.random(30)
print(A)
n = A.mean()
print(n)

#10task

print("task 10")

A = np.zeros((8,8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

#11task
print("task 11")
V = np.random.random((5,5))
a,b = V.max(), V.min()
V = (V-a)/(b-a)
print(V)



#14task
print("task 14")
V = np.zeros((5,5))
V += np.arange(5)
print(V)

#15task
print("task15")
A = np.linspace(0,1,12,endpoint=True)[1:-1]
print(A)

task 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
task 2-3
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 10]
task 4
[[0 1 2]
 [3 4 5]
 [6 7 8]]
task 5
1
2
4
task 6
[[[0.90537809 0.30079714 0.28902938]
  [0.19432353 0.59649884 0.99073175]
  [0.34612746 0.29878304 0.96719171]]

 [[0.38681969 0.35416715 0.03070563]
  [0.13131164 0.92353846 0.39425357]
  [0.22455721 0.28033259 0.82716186]]

 [[0.49602254 0.61377837 0.49475836]
  [0.80205943 0.92460029 0.9829197 ]
  [0.64130713 0.08565489 0.21028503]]]
task 7
min is: 0.022350982480217274 max is: 0.9971585471866906
task 8
[0.17735229 0.34472032 0.35842836 0.11199384 0.71063034 0.99743388
 0.38430306 0.4539159  0.64433515 0.11940725 0.18821167 0.60003487
 0.47993324 0.706302   0.47926694 0.35686282 0.54624001 0.1134745
 0.78733163 0.39251123 0.6286187  0.607828