In [1]:
import numpy as np

In [1]:
# Requirements:
# install numpy
import numpy as np

# 1
x = np.zeros(10)
x[5] = 1
print('Result null vector of size 10:\n', x)

# 2
x = np.arange(10, 50)
print('\nResult ranging values:\n', x)

# 3
x = x[::-1]
print('\nResult reverse vector:\n', x)

# 4
x = np.arange(0, 9).reshape(3, 3)
print('\nResult 3x3 matrix ranging from 0 to 8:\n', x)

# 5
x = np.array([1, 2, 0, 0, 4, 0])
y = np.nonzero(x)
print('\nResult indices of non-zero elements:\n', y)

# 6
x = np.random.randint(1, 100, (3, 3, 3))
print('\nResult of 3x3x3 array with random values:\n', x)

# 7
x = np.random.randint(1, 100, (10, 10))
_min = x.min()
_max = x.max()
print('\nResult random values 10x10:\n', x)
print('Min: ', _min, '\nMax: ', _max)

# 8
x = np.random.randint(1, 100, 10)
mean = x.mean()
print('\nResult random values of size 10:\n', x)
print('Mean: ', mean)

# 9
x = np.ones((5, 5))
print('\nOriginal array:\n', x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print('Bordered array with 0`s:\n', x)

# 10
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print('\nCheckerboard pattern:\n', x)

# 11
x = np.random.randint(1, 10, (3, 3))
print('\nOriginal matrix:\n', x)
_min = x.min()
_max = x.max()
x = (x - _min)/(_max - _min)
print('Normalized matrix:\n', x)

# 12
x = np.arange(10)
print('\nOriginal array: ', x)
x[(3 < x) & (x <= 8)] *= -1
print('Negate array: ', x)

# 13
x = np.arange(5)
y = np.arange(10)
print('\nArray 1: ', x)
print('Array 2: ', y)
print('Common values between two arrays: ', np.intersect1d(x, y))

# 14
x = np.zeros((5, 5))
x += np.arange(5)
print('\nMatrix 5x5 with row values ranging from 0 to 4:\n', x)

# 15
x = np.linspace(0, 1, 11, endpoint=False)[1::]
y = np.random.random(10)
print('\nVector of size 10 with values ranging from 0 to 1, both excluded:\n', x)

Result null vector of size 10:
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

Result ranging values:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Result reverse vector:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]

Result 3x3 matrix ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Result indices of non-zero elements:
 (array([0, 1, 4]),)

Result of 3x3x3 array with random values:
 [[[70 85 70]
  [32 71 48]
  [96 41  2]]

 [[55 90 74]
  [21 17 24]
  [22  9 70]]

 [[12 65 82]
  [99 85 49]
  [72 74 12]]]

Result random values 10x10:
 [[55  2 44  1 33 88 77 55  3 64]
 [83 53 42 66 84 53 39 35 84 77]
 [66 69  5 13 25 94 48 20 64 42]
 [59 51 57  2 40 29 51 41  2 25]
 [25 61 22 81 99 54 16 65 82 86]
 [ 5 42 18 25 25  1 16 75 61 76]
 [36 10 79 29 15 72 83 90 84 89]
 [87 73 17 70 97 84 70 70  8 86]
 [51 46 77 41 35 40 97  7 58 86]
 [83 14 50 24 70 1